# Generated by Django 5.1 on 2025-05-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_patients"),
        ("medical_records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="staff_access",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="can_access_records",
                to="employees.employee",
            ),
        ),
    ]
