# Generated by Django 5.1 on 2025-05-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0003_department_employees"),
        ("medical_records", "0002_medicalrecord_staff_access"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalrecord",
            name="department",
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="added_department_records",
                to="departments.department",
            ),
        ),
    ]
