# Generated by Django 5.1 on 2025-05-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0003_department_employees"),
        ("employees", "0002_employee_patients"),
        ("medical_records", "0003_remove_medicalrecord_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                related_name="added_department_records",
                to="departments.department",
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="diagnosis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="staff_access",
            field=models.ManyToManyField(
                blank=True, related_name="can_access_records", to="employees.employee"
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="treatment_plan",
            field=models.TextField(blank=True, null=True),
        ),
    ]
