# Generated by Django 5.1 on 2025-05-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0004_alter_medicalrecord_departments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="family_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="symptoms",
            field=models.TextField(blank=True, null=True),
        ),
    ]
