# Generated by Django 5.1 on 2025-05-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0005_medicalrecord_family_history_medicalrecord_symptoms"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicalrecord",
            old_name="family_history",
            new_name="alergies",
        ),
        migrations.RenameField(
            model_name="medicalrecord",
            old_name="treatment_plan",
            new_name="familyHistory",
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="patientHistory",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="pre_existingConditions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="treatmentPlan",
            field=models.TextField(blank=True, null=True),
        ),
    ]
