# Generated by Django 5.1 on 2025-05-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_initial"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="employees",
            field=models.ManyToManyField(
                blank=True, related_name="departments", to="employees.employee"
            ),
        ),
    ]
