# Generated by Django 5.1 on 2025-05-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="patients",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_employees", to="patients.patient"
            ),
        ),
    ]
